export const UPDATE_STARTING_SEASON = 'UPDATE_STARTING_SEASON';
export const UPDATE_LUXURY_PAYROLL = 'UPDATE_LUXURY_PAYROLL';
export const UPDATE_MIN_PAYROLL = 'UPDATE_MIN_PAYROLL';
export const UPDATE_LUXURY_TAX = 'UPDATE_LUXURY_TAX';
export const UPDATE_MAX_CONTRACT = 'UPDATE_MAX_CONTRACT';
export const UPDATE_SALARY_CAP = 'UPDATE_SALARY_CAP';
